dist: xenial
group: edge

language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
env:
  - TOXENV=django
  - TOXENV=nodjango
  - TOXENV=coverage

sudo: true  # Allow the sudo command

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-12 postgresql-client-12 postgresql-12-postgis-2.5 postgresql-12-postgis-2.5-scripts
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,12}/main/pg_hba.conf
  - sudo cp /etc/postgresql/{10,12}/main/pg_hba.conf
  - sudo service postgresql restart 12
install:
  - pip install frozendict
  - pip install sqlalchemy
  - pip install GeoAlchemy2
  - pip install psycopg2-binary
  - pip install coveralls
  - pip install tox

before_script:
  - psql -c 'CREATE ROLE django SUPERUSER LOGIN CREATEDB;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - psql -c 'CREATE DATABASE test_pg_database;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_pg_database
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d test_pg_database
script:
  - tox
after_success:
  coveralls
